language: python
python:
 - "2.7"

install:
 - pip install -r requirements.txt

script:
 - python manage.py test 

deploy:
  provider: openshift
  user: "hugobarzano@gmail.com"
  password: "root1993" 
  domain: "hugobarzano"
  app: computer

after_deploy:
  - python manage.py syncdb --noinput
    
