FROM ubuntu:latest

#Autor
MAINTAINER Hugo Barzano Cruz <hugobarzano@gmail.com>

#Actualizar Sistema Base
RUN sudo apt-get -y update

#Descargar aplicacion
RUN sudo apt-get install -y git
RUN sudo git clone https://github.com/hugobarzano/pruebas_IV.git

# Instalar Python y PostgreSQL
RUN sudo apt-get install -y python-setuptools
RUN sudo apt-get -y install python-dev
RUN sudo apt-get -y install build-essential
RUN sudo apt-get -y install python-psycopg2
RUN sudo apt-get -y install libpq-dev
RUN sudo easy_install pip
RUN sudo pip install --upgrade pip

#pruebas
RUN apt-get install -y python-software-properties software-properties-common postgresql-9.3 postgresql-client-9.3 postgresql-contrib-9.3

#CReacion base de datos
RUN echo "postgres ALL = (ALL) ALL" >> /etc/sudoers 
USER postgres
RUN /etc/init.d/postgresql start
RUN ls
RUN /etc/init.d/postgresql start
EXPOSE 5432
RUN sudo -u postgres psql -c "CREATE USER docker5 PASSWORD 'docker'"
RUN sudo -u postgres psql -c "ALTER ROLE docker WITH SUPERUSER"
RUN sudo -u postgres psql -c "CREATE DATABASE docker WITH OWNER docker"
RUN sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE docker TO docker"

RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.3/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/9.3/main/postgresql.conf



#Instalamos la aplicacion
RUN ls
RUN cd osl-computer-management/ && ls -l
RUN cd osl-computer-management/ && cat requirements.txt
RUN cd osl-computer-management/ && sudo pip install -r requirements.txt

#Realizamos migraciones
RUN cd osl-computer-management/ && python manage.py syncdb --noinput
