db:
  image: postgres
web:
  image:  hugobarzano/osl-computer-management:computer-management
  #command: sh -c "cd /osl-computer-management && ls"
  #command: sh -c "cd /osl-computer-management/ProyectoDjango && cat settings.py"
  #command: sh -c "cd /osl-computer-management && python manage.py syncdb --noinput"
  #command: sh -c "ifconfig"
  command: sh -c "pwd && ls && ifconfig && cd /osl-computer-management && python manage.py syncdb --noinput && sudo python manage.py runserver 0.0.0.0:8000"

  ports:
    - "80:8000"
    - "5432:5432"
  links:
    - db
  environment:
    - COMPOSE=true
